#!/bin/bash
set -e # exit on any failure
set -o pipefail # any step in pipe caused failure
set -u # undefined variables cause exit


# ensure the working dir is the repo root
SCRIPT_DIR=$(realpath $(dirname "$0"))
REPO_ROOT=$SCRIPT_DIR/../..
cd $REPO_ROOT
GCR_PATH=gcr.io/sanche-testing-project/logging:latest
PUBSUB_TOPIC=logging-test

build_container() {
  docker build -t $GCR_PATH --file $SCRIPT_DIR/test_code/Dockerfile $REPO_ROOT
  docker push $GCR_PATH
}

logs() {
  local OFFSET="${1:-10}"
  echo "resource filter: \"$(filter-string)\""
  echo "printing from last $OFFSET mins..."
  TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ"  --date "-$OFFSET min")
  gcloud logging read "$(filter-string) AND timestamp > \"$TIMESTAMP\""
}

trigger() {
  local FUNCTION="${1-empty}"
  if [[ $FUNCTION == "empty" ]]; then
    echo "function not set"
    exit 1
  fi
  gcloud pubsub topics publish "$PUBSUB_TOPIC" --message="$FUNCTION"
}

ENVIRONMENT=${1:-none}
if [[ -f "$SCRIPT_DIR/env_scripts/$ENVIRONMENT.sh" ]]; then
  source "$SCRIPT_DIR/env_scripts/$ENVIRONMENT.sh"
else
  echo not a valid environment: $ENVIRONMENT
fi
shift
ACTION=${1:-none}
set -u
if [[ "$(type -t $ACTION)" == "function" ]]; then
  shift
  $ACTION $@
else
  echo not valid command: $ACTION
  exit 1
fi
